### ISSUE TITLE
ME Export bus driver bug?

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#1137]
Hi there,

after playing around a bit with an export bus attached to an adapter with a database upgrade I found that setting the export config works fine. But after one exportIntoSlot(direction,slot) that works it actually makes the export bus export no more items anymore. Only workaround I found was replacing the export bus. Using appliedenergistics2-rv2-beta-33 and OpenComputers-MC1.7.10-1.5.9.21-universal.

**Comment by fnuecke** [comment]
Not sure if it's the same thing, but found an issue with the driver that is fixed now. At least after that I could not reproduce this issue. I tested with rv2 stable, though. Confirmation would be great.

**Comment by Keridos** [comment]
Yes, this fixed it.

**Comment by kevinkk525** [comment]
Well sadly it is not fixed for me. We are using the rv2-stable and i get the following error when i try to export items: "appeng.util.ConfigManager.getSetting(java.lang.Enum)"

**Comment by fnuecke** [comment]
And that's with the latest 1.5.10-dev? If so I'll have another look.

**Comment by kevinkk525** [comment]
No with 1.5.9.21. will try the 1.5.10-dev. thanks for the reply
