### ISSUE TITLE
Open Computer `ignorePower` broken by Applied Energistics

### ISSUE THREAD

**Issue by thakyZ** [MightyPirates/OpenComputers#3123]
**Describe the bug**
AE2 doesn't like the option for Open Computers that makes all OC blocks not require power.

**To Reproduce**
First make sure the option for Open Computers that is titled `ignorePower` is set to `true`. When placing a Open Computers' tier 3 computer and then break it, right click the ground with an empty hand or another block and the computer comes back. I have tested it with only the tier 3 computer and the rack, but I am very certain that it affects other blocks.

**Expected behavior**
The blocks from open computers are not supposed to glitch out and become permanent ghost blocks

**Additional context**
I will also be reporting this to the AE2 Github Repo
There is no crash but the error that pops up every time references AE2 and this bug only happens when AE2 is installed along side the ignore power option
The log including the error:
https://pastebin.com/i1P90NHZ

**Environment**
Window 10 Pro 64-bit
Java 1.8.0.211 64-bit
Single Player

- Minecraft Version: 1.12.2
- AE2 Version: AE2 rv6 stable 6
- Forge Version: forge-14.23.5.2768
- Open Computers Version: 1.7.4.153

**Comment by payonel** [comment]
thanks for the details, I believe this is fixed in our dev builds, please retest using a recent dev build from: https://ci.cil.li/job/OpenComputers-MC1.12/

**Comment by thakyZ** [comment]
Yes it is fixed thank you

**Comment by thakyZ** [comment]
Ok it is happening again but with a Stack Overflow error and it started when I turned on ignore power but still continues even after I turned it off, it has been happening on 170 through 172 of the Open Computer's dev build
https://pastebin.com/7c9mhYA3

**Comment by payonel** [comment]
the second log you attached is a different bug, and one that I couldn't reproduce. But, I added a check that will likely stop the stackoverflow from happening again
