### ISSUE TITLE
Chunkloader doesn't work as expected

### ISSUE THREAD

**Issue by fipil** [MightyPirates/OpenComputers#440]
Hi, I'd like to use the Chunkloader. I've a lua program for robot which digs some material in a big area. The area is so big, that I cannot use the Chunkloader from Buildcraft (which works perfectly, but only on the 3x3 chunks area). So I want to use the OC Chunkloader upgrade. I put to the beginning of my program a code for activation:

local chunkloader = require("component").chunkloader
if not chunkloader.setActive(true) then
    print("Cannot activate Chunkloader.")
end
if chunkloader.isActive() then
  print("Chunkloader is ACTIVE.")
else  
  print("Chunkloader is NOT active.")
end

My program prints "Chunkloader is ACTIVE", so it seems that the chunkloader is active.
But it doesn't work. I run the program and robot is working only if I'm near.
If I log off from the server, all chunks are unloaded and robot doesn't continue working.
After loging in, I can find the robot on the same place as I left him and he continue working.

I expected, that the robot with the active Chunkloader will work alone, so I'll see any big work progress when I login after an hour or more. 
Please what's wrong? Is it a bug or am I doing something wrong?

btw: Open Component is a brilliant mod, I enjoy a lot playing with it!
Thank you!
Filip

**Comment by fnuecke** [comment]
Hmm, sounds like a bug. I did test it quite a bit, but I might have missed something / screwed something up later on. I'll look into it!

**Comment by Techokami** [comment]
Yeah I had a similar issue. I decided to not install a separate chunkloading mod, since OpenComputers provides its own. So I set up a robot next to a charger with a chunkloader upgrade installed in it, and had it idle. Next to it was a simple machine using an Ender Storage chest (linked to an Ender Storage backpack I had in my inventory) and an Extraction Tube (from the Tubes! mod) sucking contents out of said Ender Storage chest into a Diamond chest. The idea was to have a means of hauling back lots of loot from a long expedition with ease. However, when I got too far away, it stopped working. I do not think it was on a chunk boundary, so I think the chunkloader is just not doing its job in multiplayer.

**Comment by fnuecke** [comment]
Please try the latest stable or dev builds (from Jenkins, _not_ from the releases tab on Github), should be fixed in there!

**Comment by fnuecke** [comment]
http://ci.cil.li/

**Comment by fipil** [comment]
We updated server and clients to the OC 1.3.2.527 build (OpenComputers-MC1.6.4-1.3.2.527-universal.jar) and I just tested. Unfortunately it still doesn't work. After I log off, wait a while and log on again, the robot continues from the place I left him. He made no progress during time I was gone.

**Comment by fnuecke** [comment]
Hmm, could you check if he's stuck at a chunk border? That's one corner case I've only roughly tested, although it worked when I did.

**Comment by fipil** [comment]
How can I test it? When I go to the robot, it starts working, sooner than I can see him. Maybe some debug lua program, running on robot? When I tested by logging off and on, robot was always where I left him. So he didnt move at all, for a couple of steps to the border of chunk. So I think that he doesn't stuck at the chunk border. It looks like he stuck just where it is, when I log of, or go to higher distance.

We run it on the MCPC1.6.4 server.

**Comment by fnuecke** [comment]
Ah, I somehow thought I'd read it was stuck, my bad. Hard to test then. I'll see what I can find with a couple of debug prints and breakpoints.

**Comment by ph1x3r** [comment]
I have the latest build and this is still a problem.

If the robot only gets a ticket for the chunk it is in, is it possibly getting stuck when trying to cross into a new chunk that isn't loaded?

At some point, isn't the robot going to have 2 tickets? One for the chunk it is in and one for the chunk it will move into?

Perhaps this is why RC uses a 3x3 chunk size so that it always has neighbouring chunks loaded.

Edit: I am going to have to check this again. I was using the 'Mining World' from Aroma1997 and even the CB chunkloader wouldn't keep the robot running.

**Comment by fnuecke** [comment]
The one time I did notice something off was when reloading the actual world - I had a robot moving back and forth across a chunk border, and it's own afterimage was blocking its path... that's something I'll hopefully be able to fix... tomorrow... or so. As for the force-loaded area, from my tests the check for whether the target block is valid (before moving) actually causes a chunk load, when necessary (without needing a ticket to force load the chunk). It worked reliably in my tests, but it'd be nice to have that verified by someone else.

**Comment by fnuecke** [comment]
So yeah, this should be fixed now. Fascinatingly it worked in my testing up until now, simply because the robots moved around enough to keep the chunks loaded purely through their interaction with the world... the issue essentially was that the forced chunk wasn't being properly updated when robots moved into other chunks.

**Comment by fipil** [comment]
Finaly the chunk loader works as expected! 
Yuppieee! Great work fnuecke! Thanks a lot. :-)
Tested on MCPC1.6.4 server, OpenComputers-MC1.6.4-1.3.3.550-universal
